# Generated by Django 4.0.3 on 2022-07-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentManagement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='moradaEmpresa',
            field=models.TextField(blank=True, db_column='MoradaEmpresa', null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='nomeEmpresa',
            field=models.TextField(blank=True, db_column='NomeEmpresa', null=True),
        ),
    ]
