# Generated by Django 4.0.3 on 2022-07-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilizadores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='gabinete',
        ),
        migrations.AddField(
            model_name='administrador',
            name='parqueid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_de_nascimento',
            field=models.DateTimeField(blank=True, db_column='Data de nascimento', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='morada',
            field=models.CharField(blank=True, db_column='Morada', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nif',
            field=models.IntegerField(blank=True, db_column='NIF', null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(blank=True, db_column='Funcao', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='parqueid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
