# Generated by Django 4.0.3 on 2022-07-02 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManagement', '0002_initial'),
        ('utilizadores', '0002_remove_administrador_gabinete_administrador_parqueid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='parqueid',
            field=models.ForeignKey(db_column='ParqueID', on_delete=django.db.models.deletion.CASCADE, to='AdminManagement.parque'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='parqueid',
            field=models.ForeignKey(db_column='ParqueID', on_delete=django.db.models.deletion.CASCADE, to='AdminManagement.parque'),
        ),
    ]
