# Generated by Django 4.0.3 on 2022-07-02 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilizadores', '0003_alter_administrador_parqueid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='parqueid',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='parqueid',
        ),
    ]
